### ISSUE TITLE
Remove old pages

### ISSUE THREAD

**Issue by wschoot** [DIVD-NL/sites#138]
We use rsync (https://github.com/DIVD-NL/sites/blob/master/.circleci/config.yml#L49) to sync pages but we don't remove the old (removed) ones.

 Perhaps we should use the --delete flag

**Comment by wschoot** [comment]
It might be sufficient to do this in the config of the circleci file (so not on the webserver) but I'm not 100% sure about that part of the setup yet

**Comment by MrSeccubus** [comment]
It’s not just sufficient, that is EXACTLY where it needs to go.

Sent from my mobile device, sorry for the typyos.

On 6 Nov 2021, at 06:59, Wouter Schoot ***@***.***> wrote:

﻿

It might be sufficient to do this in the config of the circleci file (so not on the webserver) but I'm not 100% sure about that part of the setup yet

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDIVD-NL%2Fsites%2Fissues%2F138%23issuecomment-962400361&data=04%7C01%7C%7Ca79df6d7d03e4cfbd98408d9a0ea9543%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717751653513645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nJlzGoy01eiuBSbT%2F38iBhYkUTZrc3wWzhnWo28cibE%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAIDS3QSPE75LUXYQKSYWVTUKS73VANCNFSM5HL6QOLQ&data=04%7C01%7C%7Ca79df6d7d03e4cfbd98408d9a0ea9543%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717751653523636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=giKsqGRrOB5O9%2BHUXffmWCjJIoRi%2FVdQPWtDwgHaJ%2BI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca79df6d7d03e4cfbd98408d9a0ea9543%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717751653523636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5z8hZVHObcmd4tCII%2FbXDYgaBtPz9IMq72qI%2B68ScPI%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca79df6d7d03e4cfbd98408d9a0ea9543%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717751653533629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4I5Qf5ern3xirm7fosKWpo2l%2F%2BP4dbLySAl%2B0vqhFRs%3D&reserved=0>.

**Comment by therealprocyon** [comment]
Should this be directly added to a branch and then merged or should someone test this first? I suppose that it would probably work fine but don't think gambling it is wise

**Comment by MrSeccubus** [comment]
I’ll make the change on Monday. This part is only executed on a commit to master.
There is a chance the supp.json file gets removed, so need to figure out a strategy for that.

Sent from my mobile device, sorry for the typyos.

On 6 Nov 2021, at 09:04, TheRealProcyon ***@***.***> wrote:

﻿

Should this be directly added to a branch and then merged or should someone test this first? I suppose that it would probably work fine but don't think gambling it is wise

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDIVD-NL%2Fsites%2Fissues%2F138%23issuecomment-962415594&data=04%7C01%7C%7Ceeedb67b1565450b357208d9a0fc0a3e%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717826630824281%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3XadzcPo6wxcZMeEPbYMZ%2BxYite8Arfae%2FeRHZT3DAs%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAIDS3W6QXGRZ5ISUS6BVALUKTOQJANCNFSM5HL6QOLQ&data=04%7C01%7C%7Ceeedb67b1565450b357208d9a0fc0a3e%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717826630834270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Rk64B6kQ%2FhlD%2FuNa1xbixRwAVklDbS0lLhEiGl88l4U%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ceeedb67b1565450b357208d9a0fc0a3e%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717826630844266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N8mT6EMjEnF93G0jjU2u%2BsSkCpQigjoT72RLh9pIWng%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ceeedb67b1565450b357208d9a0fc0a3e%7Cdb27021b05df420391f71dc8f2fa0f3b%7C1%7C0%7C637717826630844266%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Lw%2BYN%2BMw3b6RGHKhuMkzgQCg7AposaqWhEB12B1UAK8%3D&reserved=0>.
